"""Auto-generated migration

Revision ID: 04cf3206bb7a
Revises: c23c3f620426
Create Date: 2025-12-14 22:12:32.224387

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '04cf3206bb7a'
down_revision: Union[str, None] = 'c23c3f620426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
